#!/bin/bash
# script to control the firewall, start and stop for now
LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/settings.conf'

if [ "$1" = "start" ]; then
	#this needs a loop to check if tun0 exists ... later
	if [ ! "$1" = "quite" ] && [ ! "$2" = "quite" ]; then
		echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- turning port forwarding ON"
	fi

    if [ "$OS_TYPE" = "Linux" ]; then
      /usr/local/pia/include/fw-iptables-forward.sh
    else
      /usr/local/pia/include/fw-pf-forward.sh
    fi
	exit
fi


if [ "$1" = "stop" ] || [ "$2" = "stop" ]; then
	if [ ! "$1" = "quite" ] && [ ! "$2" = "quite" ]; then
		echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- turning port forwarding OFF"
	fi

    if [ "$OS_TYPE" = "Linux" ]; then
      /usr/local/pia/include/fw-iptables-no-forward.sh
    else
      /usr/local/pia/include/fw-pf-no-forward.sh
    fi
	exit
fi


if [ "$1" = "fix" ]; then
	printf "\n" >> /usr/local/pia/cache/network.log
	echo $(date +"%Y-%m-%d %H:%M:%S")\
    "script pia-forward fix needs to run ... network status right now" >> /usr/local/pia/cache/network.log
    ifconfig "$IF_TUNNEL" &>> /usr/local/pia/cache/network.log
    ifconfig "$IF_EXT" &>> /usr/local/pia/cache/network.log
    ifconfig "$IF_INT" &>> /usr/local/pia/cache/network.log
    netstat -rn &>> /usr/local/pia/cache/network.log


	if [ ! "$1" = "quite" ] && [ ! "$2" = "quite" ]; then
		echo -e "[\e[1;33mwarn\e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- will attempt to stop any VPN tunnels \n\tand restart all network interfaces"

		killall openvpn 2>/dev/null
        rm -f /usr/local/pia/cache/status.txt 2>/dev/null
		/usr/local/pia/include/fw-no-forward.sh
		# restart networking to get default routes through em0 working again
		# service network restart #CentOS
		ifdown "$IF_EXT" && ifup "$IF_EXT" #Debian
	else
		killall openvpn 2>/dev/null
		/usr/local/pia/include/fw-no-forward.sh
		ifdown "$IF_EXT" 2>/dev/null && ifup "$IF_EXT" 2>/dev/null
	fi

	echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")" - Done! Please try again."

	printf "\n" >> /usr/local/pia/cache/network.log
	echo $(date +"%Y-%m-%d %H:%M:%S")\
	        "network status after run" >> /usr/local/pia/cache/network.log
	ifconfig "$IF_TUNNEL" &>> /usr/local/pia/cache/network.log
	ifconfig "$IF_EXT" &>> /usr/local/pia/cache/network.log
	ifconfig "$IF_INT" &>> /usr/local/pia/cache/network.log
	netstat -rn &>> /usr/local/pia/cache/network.log
	printf "\nforward fix done"

fi
