#!/bin/bash
# script to update everything in /usr/local/pia/ from the GitRepo
LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/settings.conf'

clear
echo "getting updates from https://github.com/KaiserSoft/PIA-Tunnel"
cd /usr/local/pia/
"$CMD_GIT" config core.fileMode false
"$CMD_GIT" reset --hard HEAD

"$CMD_GIT" pull origin 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

"$CMD_GIT" submodule init htdocs/plugin/phpdhcpd 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

"$CMD_GIT" submodule update htdocs/plugin/phpdhcpd 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

"$CMD_GIT" submodule init htdocs/plugin/parsedown 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

"$CMD_GIT" submodule update htdocs/plugin/parsedown 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi


#run pia-setup to fix permissions from git pull
echo
chmod ugo+x /usr/local/pia/pia-setup
/usr/local/pia/pia-setup


echo "Showing the last 3 commit messages"
"$CMD_GIT" --no-pager log -n 3 --pretty="format:%ci%n>> %s <<%n"
