#!/bin/bash
# script to end the tunnel and reset the system back to normal
# note: restarting the network to get the default route back in place

LANG=en_US.UTF-8
export LANG

killall openvpn

iptables -F
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

#development rules, need to think about port 22
iptables -A INPUT -i eth0 -p tcp --dport 22 -j ACCEPT
iptables -A OUTPUT -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT

# restart networking to get default routes through eth0 working again
# service network restart #CentOS
ifdown eth0 && ifup eth0 #Debian
