#!/bin/bash
# script to create links to the pia scripts and set permissions

LANG=en_US.UTF-8
export LANG

# the ping functions now require dig
if [ ! -f "/usr/bin/dig" ]; then
	apt-get -y install dnsutils > /dev/null
fi
# pia-daemon will need screen soon
if [ ! -f "/usr/bin/screen" ]; then
	apt-get -y install screen > /dev/null
fi
# add php5-cli for pia-daemon 2.0
if [ ! -f "/usr/bin/php" ]; then
    apt-get -y install php5-cli php5-curl
fi

#create a new login.conf if none exists
if [ ! -f '/pia/login.conf' ]; then
	echo "your PIA account name on this line" > '/pia/login.conf'
	echo "your PIA account password on this line" >> '/pia/login.conf'
fi

#create a fresh settings file
if [ ! -f "/pia/settings.conf" ]; then
	echo '#!/bin/bash' > '/pia/settings.conf'
	echo 'LANG=en_US.UTF-8' >> '/pia/settings.conf'
	echo 'export LANG' >> '/pia/settings.conf'
	echo '' >> '/pia/settings.conf'
	echo '' >> '/pia/settings.conf'
	echo '# interface and network settings' >> '/pia/settings.conf'
	echo '#####' >> '/pia/settings.conf'
	echo '# name of your external interface. this connects to the Internet/Router' >> '/pia/settings.conf'
	echo 'IF_EXT="eth0"' >> '/pia/settings.conf'
	echo '# name of your internal interface. this if for the private VM network' >> '/pia/settings.conf'
	echo 'IF_INT="eth1"' >> '/pia/settings.conf'
	echo '# name of your VPN interface' >> '/pia/settings.conf'
	echo 'IF_TUNNEL="tun0"' >> '/pia/settings.conf'
	echo '' >> '/pia/settings.conf'
fi

FILES="pia-start pia-stop pia-status pia-update"
FILES="$FILES pia-setup pia-forward  pia-prepare-ovpn pia-daemon"
for f in $FILES
do
	if [ -f "/bin/$f" ]; then
		rm "/bin/$f"
	fi
	ln -s "/pia/$f" "/bin/$f"
	chmod u+x "/pia/$f"
done

#handle files in include, these don't get /bin/ links
FILES="fw-forward fw-no-forward functions.inc build_ping_list"
for f in $FILES
do
	chmod u+x "/pia/include/$f"
done



#check ip cache
if [ ! -f "/pia/include/ip_list.txt" ]; then
	echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
	  "- ip_list.txt does not exist - rebuilding!"
	echo -e "\tthis will take a couple of minutes...."
	/pia/include/build_ping_list
fi



#add missing settings to settings.conf
/pia/include/fix_settings



#ALWAYS RUN THIS LAST
chown -R root.root /pia
chmod -R og-rwx /pia