#!/bin/bash
# starts a specific VPN connection
# The argument must be the name of the .ovpn file without .ovpn
#	./start-vpn Germany
# get a list of connection names with ./start-vpn list

LANG=en_US.UTF-8
export LANG
source '/pia/settings.conf'
source '/pia/include/functions.inc'

# generate a few IPs for the uptime functions
gen_ip_list

#show usage
if [ "$1" = "list" ] || [ $# -eq 0 ] || [ "$1" = "--help" ]; then
	LIST=`ls -1 /pia/ovpn/ | gawk -F"." '{print $1}'`
	
	echo
	echo "Listing available VPN connections:"
	echo "$LIST"
	echo
	echo "Examples:"
	echo -e "\tpia-start Germany"
	echo -e "\tpia-start \"UK London\""
	exit
fi


#execute if .ovpn file exists with name passed
if [ -f "/pia/ovpn/$1.ovpn" ]; then
	#check the for default value
	PIA_UN=`sed -n '1p' /pia/login.conf`
	if [ "$PIA_UN" = "your PIA account name on this line" ]; then
	        echo
	        echo "Please add your Private Internet Access account information"
	        echo "to /pia/login.conf"
	        echo "Try"
	        echo -e "\tvi /pia/login.conf"
	        echo "or"
	        echo -e "\tnano /pia/login.conf"
	        echo
        	exit
	fi


	#see if we have a tunnel open
	ping_host "vpn"
	if [ "$RET_PING_HOST" = "OK" ]; then
		echo -e "[ info ] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- closing current VPN tunnel."
		/pia/pia-stop quite
	else
		#set iptables to something save until the tunnel is set up
		/pia/pia-forward stop quite	
	fi

	
	
	echo -e "[ info ] "$(date +"%Y-%m-%d %H:%M:%S")\
		"- establishing a VPN connection to $1."
	echo -e "\tsee /pia/session.log for details"	
	openvpn "/pia/ovpn/$1.ovpn" &> /pia/session.log &

	
	

	# start the FW script once the VPN is up and running
	LOOP_PROTECT=0
	while true; do
	  ping_host "vpn"
	  if [ "$RET_PING_HOST" = "OK" ]; then	    
	    # get port forwarding info
	    get_forward_port
	    if [ "$RET_FORWARD_PORT" != "FALSE" ]; then
	      TUN_IP=`/sbin/ip addr show $IF_TUNNEL | grep -w "inet" | gawk -F" " '{print $2}' | cut -d/ -f1`
	      fw_port_forward="$TUN_IP:$RET_FORWARD_PORT"
	    else
	      fw_port_forward=""
	    fi
	    
	    # show connection data
	    echo -e "[\e[1;32m ok \e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
		    "- VPN connection to $1 established $fw_port_forward"				    
	    /pia/pia-forward start
	    #/pia/pia-status
	    break
	  fi
	  
	  
	  #endless loop protect, about 30 seconds
	  if [ "$LOOP_PROTECT" -eq 30 ]; then
		echo -e "[\e[1;31m error \e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- VPN connection error - please check /pia/session.log for details."
	    killall openvpn 2>/dev/null
	    /pia/pia-forward stop quite
	    exit
	  else
		sleep 1
		LOOP_PROTECT=$(($LOOP_PROTECT + 1))
	  fi
	done
fi