#!/bin/bash
# script to prepare the "raw" .ovpn files from PIA
# https://www.privateinternetaccess.com/openvpn/openvpn.zip
# only run this after a fresh download or if you know why you want to run it :)

# hardcode path to PIA ca.cert file into a .ovpn files
sed -i 's/ca ca.crt/ca \/pia\/ovpn\/ca.crt/g' /pia/ovpn/*.ovpn

# use login.conf to store the password localy instead of prompting for it
sed -i 's/auth-user-pass/auth-user-pass\ \/pia\/login.conf/g' /pia/ovpn/*.ovpn

echo "Files have been updated"