#!/bin/bash
# script to end the tunnel and reset the system back to normal
# note: restarting the network to get the default route back in place

LANG=en_US.UTF-8
export LANG


if [ "$1" = "verbose" ]; then

    /pia/include/socks-stop.sh

	killall openvpn

	#disable forwarding
	/pia/pia-forward stop

	# restart networking to get default routes through eth0 working again
	# service network restart #CentOS
	ifdown eth0 && ifup eth0 #Debian
	ifdown eth1 && ifup eth1 #Debian

else
    /pia/include/socks-stop.sh &>/dev/null
	killall openvpn &>/dev/null
	/pia/pia-forward stop quite
	ifdown eth0 &>/dev/null && ifup eth0 &>/dev/null #Debian
	ifdown eth1 &>/dev/null && ifup eth1 &>/dev/null #Debian
fi

# remove old status.txt
rm -f '/pia/cache/status.txt' &>/dev/null
rm -f '/pia/cache/session.log' &>/dev/null
rm -f '/pia/cache/php_pia-start.log' &>/dev/null

exit 0