#!/bin/bash
# starts a specific VPN connection
# The argument must be the name of the .ovpn file without .ovpn
#	./start-vpn Germany
# get a list of connection names with ./start-vpn list

LANG=en_US.UTF-8
export LANG

#show usage
if [ "$1" = "list" ] || [ $# -eq 0 ]; then
	LIST=`ls -1 /pia/ovpn/ | gawk -F"." '{print $1}'`
	
	echo
	echo "Listing available VPN connections:"
	echo "$LIST"
	echo
	echo "Examples:"
	echo -e "\tpia-start Germany"
	echo -e "\tpia-start \"UK London\""
	exit
fi


#execute if .ovpn file exists with name passed
if [ -f "/pia/ovpn/$1.ovpn" ]; then
	#check the for default value
	PIA_UN=`sed -n '1p' /pia/login.conf`
	if [ "$PIA_UN" = "your PIA account name on this line" ]; then
	        echo
	        echo "Please add your Private Internet Access account information"
	        echo "to /pia/login.conf"
	        echo "Try"
	        echo -e "\tvi /pia/login.conf"
	        echo "or"
	        echo -e "\tnano /pia/login.conf"
	        echo
        	exit
	fi


	#set iptables to something save until pia-fw is executed
	/pia/pia-forward stop

	echo "initiating  VPN connection. see /pia/session.log for details"
	openvpn "/pia/ovpn/$1.ovpn" &> /pia/session.log &
	

	# start the FW script once the VPN is up and running
	LOOP_PROTECT=0
	while true; do
	  TUNNEL_PING=`ping -qnw1c1 -I tun0 google.com 2>/dev/null | grep -c "0% packet loss"`
	  if [ "$TUNNEL_PING" -eq 1 ]; then
	    /pia/pia-forward start
	    /pia/pia-status
	    break
	  fi
	  sleep 1
	  
	  #endless loop protect, about 60 seconds
	  LOOP_PROTECT=$(($LOOP_PROTECT + 1))
	  if [ "$LOOP_PROTECT" -eq 60 ]; then
	    echo "unable to establish a tunnel. please check /pia/session.log for details"
	    killall openvpn 2>/dev/null
	    /pia/pia-forward stop quite
	    exit
	  fi
	done
fi