#!/bin/bash
# script to create links to the pia scripts and set permissions

LANG=en_US.UTF-8
export LANG

#set file permissions as needed
chmod 0770 /pia
find /pia -type d -exec chmod 0770 {} \;
find /pia -type f -exec chmod 0660 {} \;


# the ping functions now require dig
if [ ! -f "/usr/bin/dig" ]; then
	apt-get -y install dnsutils > /dev/null
fi
# add php5-cli for pia-daemon 2.0
if [ ! -f "/usr/bin/php" ]; then
    apt-get -y install php5-cli php5-curl
fi

#remove /bin/bash from sudoers
pos=`grep -n '/bin/bash,/sbin/shutdown' /etc/sudoers | gawk -F":" '{print $1}'`
if [ ! -z "$pos" ]; then
  sed -i /etc/sudoers -e "$pos"'s!\/bin\/bash,!!'
  if [ "$?" != "0" ]; then
    echo -e "[\e[1;31mfail\e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
      "- unable to remove bash entry from sudoers. you can fix this by getting the latest VM image."
  fi
fi

#create a new login.conf if none exists
if [ ! -f '/pia/login.conf' ]; then
	echo "your PIA account name on this line" > '/pia/login.conf'
	echo "your PIA account password on this line" >> '/pia/login.conf'
fi

#create a fresh settings file
if [ ! -f "/pia/settings.conf" ]; then
	echo '#!/bin/bash' > '/pia/settings.conf'
	echo 'LANG=en_US.UTF-8' >> '/pia/settings.conf'
	echo 'export LANG' >> '/pia/settings.conf'
	echo '' >> '/pia/settings.conf'
	echo '' >> '/pia/settings.conf'
	echo '# interface and network settings' >> '/pia/settings.conf'
	echo '#####' >> '/pia/settings.conf'
	echo '# name of your external interface. this connects to the Internet/Router' >> '/pia/settings.conf'
	echo 'IF_EXT="eth0"' >> '/pia/settings.conf'
	echo '# name of your internal interface. this if for the private VM network' >> '/pia/settings.conf'
	echo 'IF_INT="eth1"' >> '/pia/settings.conf'
	echo '# name of your VPN interface' >> '/pia/settings.conf'
	echo 'IF_TUNNEL="tun0"' >> '/pia/settings.conf'
	echo '# IP of target computer for port forwarding - if supported by location' >> '/pia/settings.conf'
	echo 'FORWARD_IP="192.168.10.100"' >> '/pia/settings.conf'
    echo '# Enable/Disable forwarding yes/no' >> '/pia/settings.conf'
    echo 'FORWARD_PORT_ENABLED="no"' >> '/pia/settings.conf'
    echo '# Enable/Disable forwarding for public LAN yes/no' >> '/pia/settings.conf'
    echo 'FORWARD_PUBLIC_LAN="yes"' >> '/pia/settings.conf'
    echo '# Enable/Disable forwarding for private VM LAN yes/no' >> '/pia/settings.conf'
    echo 'FORWARD_VM_LAN="yes"' >> '/pia/settings.conf'
    echo '# Enable ssh UI on the following interfaces' >> '/pia/settings.conf'
    echo 'FIREWALL_IF_SSH[0]="eth0"' >> '/pia/settings.conf'
    echo 'FIREWALL_IF_SSH[1]="eth1"' >> '/pia/settings.conf'
    echo '# Enable web on the following interfaces' >> '/pia/settings.conf'
    echo 'FIREWALL_IF_WEB[0]="eth0"' >> '/pia/settings.conf'
    echo 'FIREWALL_IF_WEB[1]="eth1"' >> '/pia/settings.conf'
	echo '' >> '/pia/settings.conf'
fi

FILES="pia-start pia-stop pia-status pia-update pia-settings"
FILES="$FILES pia-setup pia-forward  pia-prepare-ovpn pia-daemon"
for f in $FILES
do
	if [ -f "/bin/$f" ]; then
		rm "/bin/$f"
	fi
	ln -s "/pia/$f" "/bin/$f"
	chmod ug+x "/pia/$f"
done

#handle files in include, these don't get /bin/ links
FILES="fw-forward fw-no-forward functions.inc build_ping_list fix_settings network-interfaces.sh"
FILES="$FILES network-restart.sh autostart autostart.sh dhcpd-reconfigure.sh dhcpd-start.sh"
FILES="$FILES dhcpd-stop.sh dhcpd-status.sh update_root.sh"
for f in $FILES
do
	chmod ug+x "/pia/include/$f"
done

#reset-pia is special - ug+x but no /bin link
chmod ug+x "/pia/reset-pia"

#check ip cache
if [ ! -f "/pia/cache/ip_list.txt" ]; then
	echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
	  "- ip_list.txt does not exist - rebuilding!"
	echo -e "\tthis will take a couple of minutes...."
	/pia/include/build_ping_list
fi


#copy htdocs to /var/www
cp -r /pia/htdocs/* /var/www
rm -f /var/www/README.txt
chown -R www-data.www-data /var/www
find /var/www -type d -exec chmod 0750 {} \;
find /var/www -type f -exec chmod 0640 {} \;


#add missing settings to settings.conf
/pia/include/fix_settings



#ALWAYS RUN THIS LAST
chown -R root.vpnvm /pia
chmod -R o-rwx /pia