#!/bin/bash
# script to update settings.conf
# use like this:
#		pia-settings "NAME_OF_SETTING" "VALUE_OF_SETTING"
LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/settings.conf'


if [ ! "$1" = "" ]; then
    #escape arrays or sed will fail MYVPN[0] => MYVPN\[0]
    escaped=`echo "$1" | sed -e 's/\[/\\\[/g'`

    #update settings
    sed -i "s/$escaped=.*/$escaped='$2'/" /usr/local/pia/settings.conf
fi