#!/bin/bash
# script to update settings.conf
# use like this:
#		pia-settings "NAME_OF_SETTING" "VALUE_OF_SETTING"
LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/settings.conf'


if [ ! "$1" = "" ]; then
    #escape arrays or sed will fail MYVPN[0] => MYVPN\[0]
    escaped=`echo "$1" | sed -e 's/\[/\\\[/g'`


	if [ -f '/usr/local/bin/gawk' ]; then
		#FreeBSD
		sed -i '' "s/$escaped=.*/$escaped='$2'/" /usr/local/pia/settings.conf
	else
		#Debian
		#sed -i "s/$escaped=.*/$escaped='$2'/" /usr/local/pia/settings.conf
		sed "s/$escaped=.*/$escaped='$2'/" /usr/local/pia/settings.conf > /usr/local/pia/cache/settings.tmp
		mv /usr/local/pia/cache/settings.tmp /usr/local/pia/settings.conf
                chown root:vpnvm /usr/local/pia/settings.conf
	fi
    chmod 0660 /usr/local/pia/settings.conf
fi
