#!/bin/bash
# script to control the firewall, start and stop for now
LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/settings.conf'

if [ "$1" = "start" ]; then
	#this needs a loop to check if tun0 exists ... later
	if [ ! "$1" = "quite" ] && [ ! "$2" = "quite" ]; then
		echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- turning port forwarding ON"
	fi

	/usr/local/pia/include/fw-forward.sh
	exit
fi


if [ "$1" = "stop" ] || [ "$2" = "stop" ]; then
	if [ ! "$1" = "quite" ] && [ ! "$2" = "quite" ]; then
		echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- turning port forwarding OFF"
	fi
	/usr/local/pia/include/fw-no-forward.sh
	exit
fi


if [ "$1" = "fix" ]; then
	if [ ! "$1" = "quite" ] && [ ! "$2" = "quite" ]; then
		echo -e "[\e[1;33mwarn\e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- will attempt to stop any VPN tunnels \n\tand restart all network interfaces"

		killall openvpn 2>/dev/null
        rm -f /usr/local/pia/cache/status.txt 2>/dev/null
		/usr/local/pia/include/fw-no-forward.sh
		# restart networking to get default routes through em0 working again
		# service network restart #CentOS
		ifdown em0 && ifup em0 #Debian
	else
		killall openvpn 2>/dev/null
		/usr/local/pia/include/fw-no-forward.sh
		ifdown em0 2>/dev/null	 && ifup em0 2>/dev/null
	fi

	echo -e "[info] "$(date +"%Y-%m-%d %H:%M:%S")" - Done! Please try again."
fi