#!/bin/bash
# script to update everything in /pia/ from the GitRepo
LANG=en_US.UTF-8
export LANG

clear
echo "getting updates from https://github.com/KaiserSoft/PIA-Tunnel"
cd /pia/
git config core.fileMode false
git reset --hard HEAD

git pull origin 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

git submodule init htdocs/plugin/phpdhcpd 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

git submodule update htdocs/plugin/phpdhcpd 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

git submodule init htdocs/plugin/parsedown 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi

git submodule update htdocs/plugin/parsedown 2>&1
if [ "$?" -ne "0" ]; then
  # error updating repo, abort
  exit 1
fi


#run pia-setup to fix permissions from git pull
echo
chmod u+x /pia/pia-setup
/pia/pia-setup


echo "Showing the last 3 commit messages"
git --no-pager log -n 3 --pretty="format:%ci%n>> %s <<%n"