#!/bin/bash
# script to control the firewall, start and stop for now
LANG=en_US.UTF-8
export LANG
source '/pia/settings.conf'

if [ "$1" = "start" ]; then
	#this needs a loop to check if tun0 exists ... later
	
	echo "setting up iptables for forwarding"
	/pia/fw-forward	
	exit
fi


if [ "$1" = "stop" ]; then
	echo "disabeling port forwarding"
	/pia/fw-no-forward
	exit
fi


if [ "$1" = "fix" ]; then
	echo "will attempt to stop any VPN tunnels and restart all network interfaces"
	killall openvpn
	
	/pia/fw-no-forward
	
	# restart networking to get default routes through eth0 working again
	# service network restart #CentOS
	ifdown eth0 && ifup eth0 #Debian
	echo ""
	echo "Done! Please try again."
	exit
fi