#!/bin/bash
# will delete any cache files and create login files and settings.conf
# this command is named reset-pia on purpose (pia-reset). DO NOT run this for fun!

LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/include/commands.sh'

# pull update first
/usr/local/pia/pia-update


#clear existing ssh key
cd /etc/ssh/ ; rm -f *key*
if [ -f "/usr/sbin/dpkg-reconfigure" ]; then
	/usr/sbin/dpkg-reconfigure openssh-server
fi

rm -rf /root/.ansible
rm -rf /root/.viminfo
rm /root/.ssh/* &> /dev/null
echo "" > /root/.bash_history
cd /tmp/ ; rm -rf *
#delete all files in /var/log
find /var/log -type f -delete
rm -rf /usr/local/pia/ovpn.d/* &> /dev/null

# PHP session files
if [ -d '/var/lib/php5/sessions' ]; then
    rm -f '/var/lib/php5/sessions/'*
fi


#delete and recreate dhcpd cache files
service isc-dhcp-server stop
# Debian 
if [ -d '/var/lib/dhcp/' ]; then
    cd /var/lib/dhcp/ ; rm -f *.leases
    cd /var/lib/dhcp/ ; rm -f *.leases~
    cd /var/lib/dhcp/ ; touch dhcpd.leases
fi

rm -f /tmp/dhcpd.leases* &> /dev/null ; touch /tmp/dhcpd.leases &> /dev/null


#delete pia-* files
rm -f /usr/local/pia/login-*.conf
FILES="session.log login.conf client_id status.txt include/status.txt"
for f in $FILES
do
	if [ -f "/usr/local/pia/$f" ]; then
		rm -f "/usr/local/pia/$f"
	fi
done

#delete cache files
rm -rf "/usr/local/pia/cache/"


#delete settings.conf
rm -f /usr/local/pia/settings.conf


# clear cache and SWAP
if [ -f "/sbin/sysctl" ]; then
	sync && /sbin/sysctl vm.drop_caches=3 && swapoff -a && swapon -a
else
	sync && swapoff -a && swapon -a
fi


# reset the git repo to the last know commit and pull
cd /usr/local/pia ; /usr/local/bin/git reset --hard HEAD &> /dev/null

#Now run setup to get settings back and apply permissions
chmod 0750 /usr/local/pia/include/set_permissions.sh
/usr/local/pia/include/set_permissions.sh


rm /usr/local/pia/settings.conf
echo "Done, you must reboot or shutdown now!"