#!/bin/bash
# will delete any cache files and create login files and settings.conf
# this command is named reset-pia on purpose (pia-reset). DO NOT run this for fun!

LANG=en_US.UTF-8
export LANG


#clear existing ssh key
cd /etc/ssh/ ; rm -f *key*
if [ -f "/usr/sbin/dpkg-reconfigure" ]; then
	/usr/sbin/dpkg-reconfigure openssh-server
fi

echo "" > /root/.bash_history
cd /tmp/ ; rm -rf *
#delete all files in /var/log
find /var/log -type f -delete

#delete and recreate dhcpd cache files
service isc-dhcp-server stop
# Debian cd /var/lib/dhcp/ ; rm -f *.leases
# Debian cd /var/lib/dhcp/ ; rm -f *.leases~
# Debian cd /var/lib/dhcp/ ; touch dhcpd.leases
rm -f /tmp/dhcpd.leases* ; touch /tmp/dhcpd.leases


#delete pia-* files
rm -f /usr/local/pia/login-*.conf
FILES="session.log login.conf client_id status.txt include/status.txt"
for f in $FILES
do
	if [ -f "/usr/local/pia/$f" ]; then
		rm -f "/usr/local/pia/$f"
	fi
done

#delete cache files
rm -rf "/usr/local/pia/cache/"


#delete settings.conf
rm -f /usr/local/pia/settings.conf


# clear cache and SWAP
# Debian sync && /sbin/sysctl vm.drop_caches=3 && swapoff -a && swapon -a
sync && swapoff -a && swapon -a

# reset the git repo to the last know commit
cd /usr/local/pia ; /usr/local/bin/git reset --hard HEAD &> /dev/null

#Now run setup to get settings back and apply permissions
chmod ugo+x /usr/local/pia/pia-setup
/usr/local/pia/pia-setup

#force wizard to start
sed -i '' 's/SETUP_WIZARD_COMPLETED="yes"/SETUP_WIZARD_COMPLETED="no"/' /usr/local/pia/settings.conf

echo "Done, reboot or shutdown now!"
