#!/bin/bash
# script to generate a list of IPs to be used when pinging
LANG=en_US.UTF-8
export LANG
source '/pia/settings.conf'
source '/pia/include/functions.inc'

HOSTS="startpage.com icann.org wikipedia.org internic.net"
HOSTS="$HOSTS google.com google.de google.co.uk google.co.jp"
HOSTS="$HOSTS wordpress.com digg.com hosteurope.de 1und1.de"
HOSTS="$HOSTS cnn.com msn.com gnu.org live.com kernel.org"
HOSTS="$HOSTS weather.com whitehouse.gov strato.de hetzner.de"
HOSTS="$HOSTS webhostingtalk.com gandi.net rackspace.com arstechnica.com"
HOSTS="$HOSTS spiegel.de thetimes.co.uk nytimes.com slashdot.org"
HOSTS="$HOSTS amazon.com amazon.de amazon.co.uk amazon.co.jp"
HOSTS="$HOSTS youtube.com youtube.de youtube.co.uk youtube.co.jp"
HOSTS="$HOSTS apple.com apple.de apple.co.uk apple.co.jp"
HOSTS="$HOSTS bing.com bing.de bing.co.uk bing.co.jp"
HOSTS="$HOSTS microsoft.com microsoft.de microsoft.co.uk microsoft.co.jp"
HOSTS="$HOSTS ebay.com ebay.de ebay.co.uk ebay.co.jp"

#will contain a list of IPs that can be pinged
# source is the A record for the hosts listed above
IPS=""

#used for debug in this script
VERBOSE="yes"

IPCACHE="/pia/include/ip_list.txt"


#check if the IP cache is writable. no point in running if it is not
if [ -f "$IPCACHE" ]; then
  if [ ! -w "$IPCACHE" ]; then
    echo -e "[\e[1;31m error \e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
      "- $IPCACHE is not writable?!?"
    exit
  fi
else
  touch "$IPCACHE" 2> /dev/null
  #check exit status 
  if [ "$?" = "1" ]; then
    echo -e "[\e[1;31m error \e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
      "- \"$IPCACHE\" is not writable?!?"
    exit
  fi
  #remove the empty file so aborting the process will not keep an empty file around
  rm -f "$IPCACHE" 2> /dev/null
fi


#loop over list above and get dig A for each one
for h in $HOSTS
do

  echo -e "[ info ] "$(date +"%Y-%m-%d %H:%M:%S")\
	"- Checking IPs from $h ...."

  #get list of IPs in the domain's A record
  RET_DIG=`dig "$h" +short A`
  if [ "$?" = "1" ]; then
	echo -e "[ info ] "$(date +"%Y-%m-%d %H:%M:%S")\
	"- dig failed with $RET_DIG"
	RET_DIG=""
  fi
  
  COUNT=0
  for ip in $RET_DIG
  do
    #$ip should now contain one of the records from 'dig'
    # ping each one and store them if they respond
    $attempts=4
    for (( x=0 ; x < $attempts ; x++ ))
    do
      # ping each host multiple times to ensure they are reliable
      ping_host "internet" "$ip"
      if [ "$RET_PING_HOST" = "ERROR" ]; then
		echo -e "[ info ] "$(date +"%Y-%m-%d %H:%M:%S")\
			"- ping failed $x/$attempts attempts - excluding $ip"
		break #stop on first sign of trouble
      fi
      sleep 0.2
    done
    
    # or store if the IP is "good"
    if [ "$RET_PING_HOST" = "OK" ]; then
      IPS="$IPS $ip"
      COUNT=$((COUNT + 1))
    fi
  done

done

if [ $COUNT -lt 10 ]; then
  echo -e "[\e[1;31m error \e[0m] "$(date +"%Y-%m-%d %H:%M:%S")\
    "- did not find enough IPs to generate ip_list.txt."
  echo -e "\tplease wait a few minutes then run pia-setup again."
else
  # IPS is now a string over IPs separated by space
  # loop over and write to /pia/include/ip_list.txt
  echo "# generated on "$(date +"%Y-%m-%d %H:%M:%S") > "$IPCACHE"
  for ip in $IPS
  do
    echo "$ip" >> "$IPCACHE"
  done
fi

echo -e "[ info ] "$(date +"%Y-%m-%d %H:%M:%S")\
  "- stored $COUNT IPs in ip_list.txt"
echo -e "\ttesting list by getting 10 random IPs"
#testing the generated ping list
gen_ip_list 10
for ip in ${PING_IP_LIST[@]}
do
  echo -e "\t  $ip"
done
  
