#!/bin/bash
# support script for pia-setup
# this script will add missing settings to the config file
LANG=en_US.UTF-8
export LANG
source '/pia/settings.conf'



#check if settings exist in settings.conf and add their default


if [ -z "${MYVPN[0]}" ]; then
  echo '' >> '/pia/settings.conf'
  echo '# pia-daemon settings' >> '/pia/settings.conf'
  echo '#####' >> '/pia/settings.conf'
  echo 'DAEMON_ENABLED="no"' >> '/pia/settings.conf'
  echo '# list of VPN connections to use, the first is awlays the primary' >> '/pia/settings.conf'
  echo 'MYVPN[0]="CA Toronto"' >> '/pia/settings.conf'
  echo 'MYVPN[1]="Switzerland"' >> '/pia/settings.conf'
  echo 'MYVPN[2]="Sweden"' >> '/pia/settings.conf'
  echo 'MYVPN[3]="Romania"' >> '/pia/settings.conf'
  echo 'MYVPN[4]="Germany"' >> '/pia/settings.conf'
  echo 'MYVPN[5]="France"' >> '/pia/settings.conf'
  echo 'MYVPN[6]="Netherlands"' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
  echo '# set action when VPN fails: terminate | failover' >> '/pia/settings.conf'
  echo 'FAIL_ACTION="failover"' >> '/pia/settings.conf'
  echo 'FAIL_RETRY_VPN=4' >> '/pia/settings.conf'
  echo 'FAIL_RETRY_INTERNET=3' >> '/pia/settings.conf'
  echo 'FAIL_RETRY_DELAY=1' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
fi

if [ -z ${SLEEP_INTERNET_DOWN} ]; then
  echo '' >> '/pia/settings.conf'
  echo '# General Time and Delay Settings' >> '/pia/settings.conf'
  echo '#####' >> '/pia/settings.conf'
  echo '# time in seconds to wait before rechecking a down Internet connection' >> '/pia/settings.conf'
  echo "# each run takes a few seconds to complete so don't go too low!" >> '/pia/settings.conf'
  echo '# default 320 (5 minutes)' >> '/pia/settings.conf'
  echo 'SLEEP_INTERNET_DOWN=320' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
  echo '# time in seconds to wait before attempting to ping a resource again' >> '/pia/settings.conf'
  echo '# default 4' >> '/pia/settings.conf'
  echo 'SLEEP_PING_RETEST=4' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
  echo '# time in seconds between retries when none of the PIA Gateways can be reached' >> '/pia/settings.conf'
  echo '# default 320 (5 minutes)' >> '/pia/settings.conf'
  echo 'SLEEP_RECONNECT_ERROR=320' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
  echo '# time (seconds) in between "uptime" checks. every check will send a few pings' >> '/pia/settings.conf'
  echo "# to some server so please don't flood them or they may block you" >> '/pia/settings.conf'
  echo '# default 30' >> '/pia/settings.conf'
  echo 'SLEEP_MAIN_LOOP=30' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
fi

if [ -z ${VERBOSE} ]; then
  echo '' >> '/pia/settings.conf'
  echo '# output level and debug settings' >> '/pia/settings.conf'
  echo '#####' >> '/pia/settings.conf'
  echo '# setting verbose to yes will print status notification after each check. any other settings for "background mode"' >> '/pia/settings.conf'
  echo 'VERBOSE="no"' >> '/pia/settings.conf'
  echo 'VERBOSE_DEBUG="no"' >> '/pia/settings.conf'
  echo '' >> '/pia/settings.conf'
fi

if [ -z ${bold} ]; then
  echo '' >> '/pia/settings.conf'
  echo '#for pretty print' >> '/pia/settings.conf'
  echo '#####' >> '/pia/settings.conf'
  echo 'bold=`tput bold`' >> '/pia/settings.conf'
  echo 'normal=`tput sgr0`' >> '/pia/settings.conf'
fi

if [ -z ${FORWARD_IP} ]; then
  echo '' >> '/pia/settings.conf'
  echo '# IP of target computer for port forwarding - if supported by location' >> '/pia/settings.conf'
  echo 'FORWARD_IP="192.168.10.101"' >> '/pia/settings.conf'
fi

if [ -z "${FORWARD_IP_ENABLED}" ]; then
  echo '' >> '/pia/settings.conf'
  echo '# Enable/Disable forwarding yes/no' >> '/pia/settings.conf'
  echo 'FORWARD_IP_ENABLED="yes"' >> '/pia/settings.conf'
fi

if [ -z "${DAEMON_ENABLED}" ]; then
  echo '' >> '/pia/settings.conf'
  echo '# Enable/Disable pia-daemon yes/no' >> '/pia/settings.conf'
  echo 'DAEMON_ENABLED="no"' >> '/pia/settings.conf'
fi