#!/bin/bash
# script to generate a new /etc/network/interfaces based on settings.conf
LANG=en_US.UTF-8
export LANG
source '/usr/local/pia/settings.conf'



cont="#file generated by /usr/local/pia/include/generate_interfaces.sh\n"
cont="${cont}#please use the web GUI or settings.conf to change this file\n"
cont="${cont}#or your changes may be lost when this file is refreshed\n"
cont="${cont}\n\n"
cont="${cont}# The loopback network interface\n"
cont="${cont}auto lo\n"
cont="${cont}iface lo inet loopback\n"
cont="${cont}\n"


#setup eth0
cont="${cont}# The primary network interface\n"
cont="${cont}auto $IF_EXT\n"
if [ "${IF_ETH0_DHCP}" = 'yes' ]; then
  cont="${cont}iface $IF_EXT inet dhcp\n"
else
  cont="${cont}iface $IF_EXT inet static\n"
fi

if [ "${IF_ETH0_DHCP}" = 'no' ] && [ ! -z "${IF_ETH0_IP}" ] && [ ! -z "${IF_ETH0_SUB}" ]; then
  cont="${cont}        address ${IF_ETH0_IP}\n"
  cont="${cont}        netmask ${IF_ETH0_SUB}\n"
fi
if [ "${IF_ETH0_DHCP}" = 'no' ] && [ ! -z "${IF_DEFAULTROUTER}" ] && [ ! -z "${IF_ETH0_IP}" ] && [ ! -z "${IF_ETH0_SUB}" ]; then
  cont="${cont}        gateway ${IF_DEFAULTROUTER}\n"
fi


#apply DNS when set
for dns_srv in "${NAMESERVERS[@]}"
do
  cont="${cont}        dns-nameservers ${dns_srv}\n"
done
cont="${cont}\n"


cont="${cont}# The private VM LAN interface\n"
cont="${cont}auto $IF_INT\n"
if [ "${IF_ETH1_DHCP}" = 'yes' ] && [ ! -z "${IF_ETH1_IP}" ] && [ ! -z "${IF_ETH1_SUB}" ]; then
  cont="${cont}iface $IF_INT inet dhcp\n"
else
  cont="${cont}iface $IF_INT inet static\n"
fi

if [ "${IF_ETH1_DHCP}" = 'no' ] && [ ! -z "${IF_ETH1_IP}" ] && [ ! -z "${IF_ETH1_SUB}" ]; then
  cont="${cont}        address ${IF_ETH1_IP}\n"
  cont="${cont}        netmask ${IF_ETH1_SUB}\n"
fi

cont="${cont}\n"

echo -e $cont > '/etc/network/interfaces'
