---
# install php56 


- name: install required packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - php5.6
    - php5.6-curl
#   - php5.6-mcrypt
    - php5.6-json
  notify: 
    - restart apache
  when: ansible_distribution == 'Debian'
