---
# install php56 


- name: install required packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - php
    - php-curl
    - php-mcrypt
    - php-json
  notify: 
    - restart apache
  when: ansible_distribution == 'Debian'
